#!/usr/bin/env python3
"""
extract_sprite_tail.py -- pull TempleOS DolDoc sprite (CDocBin) tails out
of a .HC file and emit one C header with a `const uint8_t` byte array
per sprite, ready to hand straight to Sprite3().

USAGE
    py extract_sprite_tail.py <file.HC> [--out-dir DIR] [--base NAME]
    (writes header to stdout by default; --out-dir also drops per-sprite
     hex-dump .txt files for spot checking)

FORMAT (verified against TempleOS source: Adam/DolDoc/DocFile.HC and
        Kernel/KernelA.HH, from cia-foundation/TempleOS.git):

    class CDocBin {
        CDocBin *next, *last;   // in-memory only
        I32      tmp_use_cnt, renum_num;  // in-memory only
        U8      *tag;           // in-memory only
        U0       start;         // <-- serialized region begins here
        U32      num;           //   BI number the doc references
        U32      flags;         //   CDocBin flags (usually 0)
        U32      size;          //   byte length of trailing data blob
        U32      use_cnt;       //   how many CDocEntry refs point at us
        U0       end;           // <-- serialized region ends here (16 bytes)
        U8      *data;          // in-memory only; on-disk `size` bytes follow inline
    };

  DocFile.HC:DocSave writes plain text, one NUL, then for each CDocBin
  with use_cnt > tmp_use_cnt: MemCpy(dst, &b->start, end-start) followed
  by MemCpy(dst, b->data, b->size). end-start is exactly 16 bytes on
  amd64 (four packed U32 fields, natural alignment; #assert !($$&7)).

  DocFile.HC:DocLoad reads them back in the same layout.

  So each entry is: [4B num][4B flags][4B size][4B use_cnt][size bytes data],
  all little-endian, tightly packed. The `data` blob for a sprite is a
  raw SPT_* opcode stream (the same bytes that Sprite3() walks).

  Sprites are not written in BI-number order; Terry writes them in
  bin_head-list order, which is roughly first-seen order after any
  DocBinsValidate() renumbering pass. Our extractor emits them sorted
  by BI so downstream code is deterministic.

  Sprites referenced with $SP,...,BP="./Foo.HC.Z,Tag"$ are pulled from
  another (potentially LZW-compressed) file at load time and DO NOT
  live in this file's tail -- so the tail's sprite count can be lower
  than the count of BI= numbers you see in the text. That's fine.
"""

import argparse
import os
import re
import struct
import sys


HEADER_STRUCT = struct.Struct('<IIII')  # num, flags, size, use_cnt
HEADER_SIZE = HEADER_STRUCT.size        # 16

# Valid SPT_* opcode values (from firmware/templeshrine/src/sprite_decoder.h).
VALID_SPT = set(range(0, 30))


def parse_tail(tail: bytes):
    """Walk the CDocBin list at `tail`. Yields dicts per entry:
       {tail_off, num, flags, size, use_cnt, data}."""
    off = 0
    while off + HEADER_SIZE <= len(tail):
        num, flags, size, use_cnt = HEADER_STRUCT.unpack_from(tail, off)
        payload_off = off + HEADER_SIZE
        if payload_off + size > len(tail):
            raise ValueError(
                f"CDocBin at tail offset 0x{off:04x} claims size={size} but "
                f"only {len(tail) - payload_off} bytes remain in tail"
            )
        yield {
            'tail_off': off,
            'num': num,
            'flags': flags,
            'size': size,
            'use_cnt': use_cnt,
            'data': tail[payload_off:payload_off + size],
        }
        off += HEADER_SIZE + size
    if off != len(tail):
        # Trailing garbage -- warn but don't crash. Real files are exact.
        sys.stderr.write(
            f"warning: {len(tail) - off} trailing bytes after last CDocBin\n"
        )


def looks_like_sprite(data: bytes) -> bool:
    """A sprite data blob starts with a valid SPT_* opcode byte.
    We accept 0..29 (see VALID_SPT). Empty payloads are not sprites."""
    return len(data) >= 1 and data[0] in VALID_SPT


def find_text_bi_numbers(text_region: bytes):
    """Return {bi_num: kinds_seen} scanned from the text region.
    kinds_seen is a set of 'SP' / 'IB' / etc. plus 'BP' if it's a
    bin-pointer reference (external file, no local binary data)."""
    text = text_region.decode('latin-1', errors='replace')
    result = {}
    # $SP,...,BI=N,...$ or $IB,...,BI=N,...$
    for m in re.finditer(r'\$([A-Z]{2})([^$]*)\$', text):
        kind, body = m.group(1), m.group(2)
        bm = re.search(r'BI=(\d+)', body)
        if not bm:
            continue
        n = int(bm.group(1))
        info = result.setdefault(n, set())
        info.add(kind)
        if 'BP=' in body:
            info.add('BP')
    return result


def emit_header(sprites, base: str, src_path: str, text_bi: dict) -> str:
    """Emit a C header string with one array per sprite (sorted by BI)."""
    lines = []
    lines.append(f"// Auto-generated by tools/extract_sprite_tail.py")
    lines.append(f"// Source: {src_path}")
    lines.append(f"// {len(sprites)} sprite(s) extracted from DolDoc tail.")
    lines.append(f"// Each array is a raw SPT_* opcode stream, ready for")
    lines.append(f"//   Sprite3(dc, x, y, z, SPRITE_{base.upper()}_BI_N,")
    lines.append(f"//           SPRITE_{base.upper()}_BI_N_SIZE);")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")

    for sp in sorted(sprites, key=lambda s: s['num']):
        n = sp['num']
        data = sp['data']
        name = f"SPRITE_{base.upper()}_BI_{n}"
        note = ""
        if n in text_bi:
            kinds = ",".join(sorted(text_bi[n]))
            note = f" (text refs: {kinds})"
        lines.append(f"// BI={n} size={len(data)} bytes use_cnt={sp['use_cnt']} first_op=0x{data[0]:02x}{note}")
        lines.append(f"#define {name}_SIZE {len(data)}u")
        lines.append(f"static const uint8_t {name}[{len(data)}] = {{")
        for i in range(0, len(data), 12):
            chunk = data[i:i + 12]
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        lines.append("};")
        lines.append("")

    # Small dispatch table so callers can index by BI at runtime.
    lines.append(f"#define SPRITE_{base.upper()}_COUNT {len(sprites)}u")
    sorted_bis = sorted(s['num'] for s in sprites)
    max_bi = max(sorted_bis) if sorted_bis else 0
    lines.append(f"#define SPRITE_{base.upper()}_MAX_BI {max_bi}u")
    lines.append(f"static const uint8_t *const SPRITE_{base.upper()}_TABLE[{max_bi + 1}] = {{")
    for i in range(max_bi + 1):
        if any(s['num'] == i for s in sprites):
            lines.append(f"    [{i}] = SPRITE_{base.upper()}_BI_{i},")
        else:
            lines.append(f"    [{i}] = 0, // BI={i} not present (external ref or unused)")
    lines.append("};")
    lines.append(f"static const uint32_t SPRITE_{base.upper()}_SIZES[{max_bi + 1}] = {{")
    for i in range(max_bi + 1):
        if any(s['num'] == i for s in sprites):
            lines.append(f"    [{i}] = SPRITE_{base.upper()}_BI_{i}_SIZE,")
        else:
            lines.append(f"    [{i}] = 0,")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def write_hex_dump(sp, out_path: str, src_path: str):
    """Drop a per-sprite hex dump alongside the header for spot checking."""
    with open(out_path, 'w') as f:
        f.write(f"# Sprite BI={sp['num']} from {src_path}\n")
        f.write(f"# tail_offset=0x{sp['tail_off']:04x}  size={sp['size']}  "
                f"flags=0x{sp['flags']:x}  use_cnt={sp['use_cnt']}\n")
        f.write(f"# first opcode = 0x{sp['data'][0]:02x}\n\n")
        for i in range(0, len(sp['data']), 16):
            row = sp['data'][i:i + 16]
            hex_part = ' '.join(f'{b:02x}' for b in row)
            ascii_part = ''.join(chr(b) if 32 <= b < 127 else '.' for b in row)
            f.write(f"{i:04x}: {hex_part:<48}  {ascii_part}\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('hc_path', help='path to a .HC DolDoc file')
    ap.add_argument('--out-dir', default=None,
                    help='write header + hex dumps to this dir (else stdout)')
    ap.add_argument('--base', default=None,
                    help='base name for arrays; defaults to file stem lower-cased')
    args = ap.parse_args()

    with open(args.hc_path, 'rb') as f:
        data = f.read()
    nul = data.find(b'\x00')
    if nul < 0:
        raise SystemExit(f"{args.hc_path}: no NUL terminator; not a DolDoc file")
    text_region = data[:nul]
    tail = data[nul + 1:]

    entries = list(parse_tail(tail))
    text_bi = find_text_bi_numbers(text_region)

    sprites = [e for e in entries if looks_like_sprite(e['data'])]
    non_sprite = [e for e in entries if not looks_like_sprite(e['data'])]

    base = args.base or os.path.splitext(os.path.basename(args.hc_path))[0].lower()

    header = emit_header(sprites, base, args.hc_path, text_bi)

    # Summary to stderr so it doesn't collide with header stdout.
    sys.stderr.write(f"{args.hc_path}: nul@{nul} tail={len(tail)}B\n")
    sys.stderr.write(f"  {len(entries)} CDocBin entr(y/ies) total, "
                     f"{len(sprites)} sprite(s), {len(non_sprite)} other\n")
    for sp in sorted(sprites, key=lambda s: s['num']):
        first32 = sp['data'][:32].hex(' ')
        sys.stderr.write(f"  BI={sp['num']:<3}size={sp['size']:>6}B  "
                         f"first32=[{first32}]\n")
    # Report BIs declared in text but missing from tail (typically BP= refs).
    text_only = sorted(set(text_bi) - {s['num'] for s in sprites})
    if text_only:
        for n in text_only:
            kinds = ",".join(sorted(text_bi[n]))
            sys.stderr.write(f"  BI={n} declared in text ({kinds}) but not in tail\n")

    if args.out_dir:
        os.makedirs(args.out_dir, exist_ok=True)
        header_path = os.path.join(args.out_dir, f"sprite_{base}.h")
        with open(header_path, 'w') as f:
            f.write(header)
        for sp in sprites:
            hex_path = os.path.join(args.out_dir, f"sprite_{base}_bi{sp['num']}.hex.txt")
            write_hex_dump(sp, hex_path, args.hc_path)
        sys.stderr.write(f"  wrote {header_path} and {len(sprites)} hex dump(s)\n")
    else:
        sys.stdout.write(header)


if __name__ == '__main__':
    main()
