#!/usr/bin/env python3
"""
parse_terry_play.py - convert a Terry Davis TempleOS song file (Play()
notation) into a C note_t[] array suitable for our badge piezo player.

Terry's Play() strings are compact tokens:
    duration letter (w/h/q/e/s/t) optionally followed by '.' for dotted
    note letter (A-G) optionally followed by '#' for sharp
    single digit (0-9) sets the current octave
    R = rest
    parens and commas ignored (slur/staccato markers we don't render)

`music.tempo = X.XXX` sets beats-per-second. Quarter note ms = 1000/X.

Notes are transposed up 2 octaves before emit so they land in the
piezo's audible band (badge piezo is ~4 kHz resonance; the mid octaves
Terry writes for a PC speaker are barely audible unshifted).

Usage:
    parse_terry_play.py <input.cpp.z> <c_symbol_name>
    -> prints a C `static const note_t <name>[] = { ... };` block
"""
import re
import sys

# Semitone offsets from C in a chromatic scale.
NOTE_OFFSET = {'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11}

# Duration in beats (where a quarter = 1).
DURATION_BEATS = {'w': 4.0, 'h': 2.0, 'q': 1.0,
                  'e': 0.5, 's': 0.25, 't': 0.125}

# Transpose all notes up by this many octaves so they land in the
# badge piezo's audible range.
OCTAVE_TRANSPOSE = 2

def midi_to_hz(midi):
    return 440.0 * (2 ** ((midi - 69) / 12))

def note_to_midi(letter, octave, sharp=False):
    # C0 = 12 in standard MIDI numbering (C-1 = 0).
    n = NOTE_OFFSET[letter] + 12 * (octave + 1)
    if sharp: n += 1
    return n

def parse_play_string(s, quarter_ms, state):
    """Parse a single Play() string body and append notes to state['notes'].

    state is a dict holding octave and duration across concatenated calls.
    """
    notes = state['notes']
    i = 0
    n = len(s)
    while i < n:
        c = s[i]
        # Duration
        if c in DURATION_BEATS:
            state['dur'] = DURATION_BEATS[c]
            state['dot'] = False
            i += 1
        elif c == '.':
            state['dot'] = True
            i += 1
        # Octave
        elif c.isdigit():
            state['octave'] = int(c)
            i += 1
        # Note
        elif c in NOTE_OFFSET:
            letter = c
            i += 1
            sharp = False
            if i < n and s[i] == '#':
                sharp = True
                i += 1
            midi = note_to_midi(letter, state['octave'] + OCTAVE_TRANSPOSE, sharp)
            hz = int(round(midi_to_hz(midi)))
            beats = state['dur'] * (1.5 if state['dot'] else 1.0)
            ms = int(round(quarter_ms * beats))
            notes.append((hz, ms))
            state['dot'] = False
        elif c == 'R':
            beats = state['dur'] * (1.5 if state['dot'] else 1.0)
            ms = int(round(quarter_ms * beats))
            notes.append((0, ms))  # rest = 0 Hz
            state['dot'] = False
            i += 1
        # Ignore grouping / articulation markers we don't render
        elif c in '(),':
            i += 1
        else:
            # Unknown char (whitespace, backslashes, etc.) - skip
            i += 1

def parse_source(path):
    # Read as bytes then decode ignoring errors (file has binary tail after
    # the source in DolDoc format).
    with open(path, 'rb') as f:
        raw = f.read()
    text = raw.decode('utf-8', errors='ignore')

    # Extract music.tempo if present. Default to Terry's Music.HC default
    # (1.0 beats/sec = quarter note = 1 second) if absent.
    tempo = 1.0
    m = re.search(r'music\.tempo\s*=\s*([0-9.]+)', text)
    if m:
        tempo = float(m.group(1))
    quarter_ms = 1000.0 / tempo

    # Extract every Play("...") string body in order. Terry's songs
    # often have Play("notes", "lyrics"), so we can't require a ")"
    # right after the closing quote — just match the first quoted
    # arg after each `Play(`.
    play_re = re.compile(r'Play\(\s*"([^"]*)"')
    calls = play_re.findall(text)

    state = {'octave': 5, 'dur': 1.0, 'dot': False, 'notes': []}
    for s in calls:
        parse_play_string(s, quarter_ms, state)
    return state['notes'], tempo

def emit_c(name, notes, tempo, src):
    out = []
    out.append(f'// Auto-generated by tools/parse_terry_play.py')
    out.append(f'// Source: {src}   music.tempo = {tempo}')
    out.append(f'// {len(notes)} notes, transposed +{OCTAVE_TRANSPOSE} octaves for piezo')
    out.append(f'static const note_t {name}[] = {{')
    per_line = 4
    for i in range(0, len(notes), per_line):
        chunk = notes[i:i+per_line]
        parts = [f'{{{hz:>5}, {ms:>4}}}' for hz, ms in chunk]
        out.append('    ' + ', '.join(parts) + ',')
    out.append('    {0, 500},   // trailing rest')
    out.append('};')
    return '\n'.join(out)

def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: parse_terry_play.py <input.cpp.z> <c_symbol_name>\n")
        sys.exit(1)
    path = sys.argv[1]
    name = sys.argv[2]
    notes, tempo = parse_source(path)
    print(emit_c(name, notes, tempo, path))

if __name__ == '__main__':
    main()
