// vocab.h — a curated ~300 iconic KJV-flavored words for the Oracle and
// the menu ticker. The full TempleOS GodWord draws from every unique word
// in the King James Bible (~12k words); this hand-picked subset covers the
// most recognizable ones and is fine for a shipping demo. Extend later by
// swapping this array for a full extracted list stored on the SD card.

#pragma once

static const char *const VOCAB[] = {
    "LORD","GOD","JEHOVAH","JESUS","CHRIST","MESSIAH","SAVIOUR","ALMIGHTY",
    "HOSTS","HOLY","SPIRIT","FATHER","SON","LAMB","KING","PRIEST","PROPHET",
    "APOSTLE","DISCIPLE","SHEPHERD","ANGEL","SERAPH","CHERUB","ARCHANGEL",
    "SATAN","DEVIL","DEMON","BEAST","DRAGON","SERPENT","VIPER",
    "LOVE","MERCY","GRACE","PEACE","FAITH","HOPE","TRUTH","WISDOM",
    "KNOWLEDGE","UNDERSTANDING","RIGHTEOUSNESS","GLORY","POWER","MAJESTY",
    "JUDGMENT","JUSTICE","MERCIFUL","GRACIOUS","BLESSED","CURSED","DIVINE",
    "SACRED","ETERNAL","EVERLASTING","INFINITE","HALLOWED","ANOINTED",
    "PRAY","PRAISE","BLESS","WORSHIP","BEHOLD","VERILY","AMEN","HEARKEN",
    "HEAR","SEEK","ASK","RECEIVE","REPENT","BELIEVE","FORGIVE","REJOICE",
    "MOURN","LAMENT","TREMBLE","MARVEL",
    "ADAM","EVE","CAIN","ABEL","NOAH","ENOCH","METHUSELAH","ABRAHAM",
    "SARAH","ISAAC","REBEKAH","JACOB","ESAU","JOSEPH","MOSES","AARON",
    "MIRIAM","JOSHUA","CALEB","GIDEON","SAMSON","SAMUEL","SAUL","DAVID",
    "SOLOMON","ELIJAH","ELISHA","ISAIAH","JEREMIAH","EZEKIEL","DANIEL",
    "JONAH","JOB","RUTH","ESTHER","MARY","MARTHA","JOHN","MATTHEW",
    "MARK","LUKE","PETER","ANDREW","JAMES","PAUL","JUDAS","STEPHEN",
    "EDEN","BABEL","UR","EGYPT","GOSHEN","MIDIAN","SINAI","HOREB",
    "CANAAN","ISRAEL","JUDAH","JERUSALEM","BETHLEHEM","NAZARETH",
    "GALILEE","JORDAN","JERICHO","SAMARIA","BABYLON","NINEVEH",
    "SODOM","GOMORRAH","GALGAL","ROME","GETHSEMANE","GOLGOTHA","EMMAUS",
    "TEMPLE","ALTAR","ARK","TABERNACLE","MERCY-SEAT","CROSS","CROWN",
    "THRONE","SCEPTRE","SWORD","SHIELD","BOW","ARROW","STAFF","ROD",
    "STAFF","MANTLE","ROBE","SANDAL","VEIL","CANDLE","LAMP","OIL",
    "INCENSE","MYRRH","FRANKINCENSE","BALM",
    "HEAVEN","EARTH","SEA","SKY","SUN","MOON","STAR","CLOUD","WATER",
    "FIRE","LIGHT","DARKNESS","WIND","STORM","RAIN","FLOOD","SNOW",
    "MOUNTAIN","VALLEY","WILDERNESS","DESERT","GARDEN","FIELD","VINE",
    "TREE","BRANCH","LEAF","FRUIT","ROOT","ROCK","STONE","DUST",
    "LION","EAGLE","DOVE","RAVEN","SPARROW","LAMB","SHEEP","GOAT",
    "OX","ASS","HORSE","COLT","FISH","LOCUST","SCORPION","OWL",
    "BREAD","WINE","HONEY","MILK","MANNA","GRAIN","SALT","HERB",
    "FIG","OLIVE","POMEGRANATE","VINEGAR","CURD",
    "SIN","SALVATION","REDEMPTION","ATONEMENT","RESURRECTION","GLORY",
    "COVENANT","COMMANDMENT","LAW","GOSPEL","PSALM","PROVERB","PROPHECY",
    "SCRIPTURE","TESTAMENT","EPISTLE","REVELATION","VISION","DREAM",
    "SOUL","SPIRIT","HEART","FLESH","BLOOD","BONE","HAND","EYE",
    "MOUTH","EAR","TONGUE","VOICE",
    "DAY","NIGHT","YEAR","AGE","MORNING","EVENING","SABBATH","JUBILEE",
    "ETERNITY","FOREVER","BEGINNING","END","GENERATION","SEASON",
    "JOY","SORROW","WRATH","ANGER","FEAR","JEALOUS","MEEK","HUMBLE",
    "PROUD","WICKED","HOLY","PURE","CLEAN","UNCLEAN","LEPER","BLIND",
    "SACRIFICE","OFFERING","BURNT","MEAL","PEACE","THANK","SIN",
    "WORD","NAME","GRACE","GIFT","PROMISE","BLESSING","OATH","VOW",
    "THIRD-DAY","MILE","STADIA","CUBIT","OMER","EPHAH","SHEKEL","TALENT",
    "FLOOD","EXODUS","PLAGUE","LOCUSTS","MANNA","QUAIL","STONE","MAGI",
    "ROOSTER","FIG-TREE","MUSTARD","WHEAT","TARE","REAP","SOW","SHEAF",
};
#define VOCAB_N (sizeof(VOCAB)/sizeof(VOCAB[0]))
